In [209]:
import pandas as pd

In [210]:
df = pd.read_csv(r'2010_2020_preTweet.csv')

In [211]:
df

,Unnamed: 0,Unnamed: 0.1,peak_date,release_date,song,artist,peak_rank,current_rank,last_rank,weeks_board,...,lyrics_score,lyrics_neg,lyrics_neu,lyrics_pos,lyrics_compound,lyrics_label,spotify_pop,spotify_id,spotify_explicit,days
0,0,0,2020-12-26,2020-12-11,Willow,Taylor Swift,1,1,NaN,1,...,"{'neg': 0.085, 'neu': 0.773, 'pos': 0.141, 'co...",0.085,0.773,0.141,0.9829,pos,82,0lx2cLdOt3piJbcaXIV74f,False,15
1,1,1,2020-12-26,2020-07-24,Mood,24kGoldn Featuring iann dior,1,5,2.0,19,...,"{'neg': 0.089, 'neu': 0.796, 'pos': 0.115, 'co...",0.089,0.796,0.115,0.9751,pos,89,4jPy3l0RUwlUI9T5XHBW2m,True,155
2,2,2,2020-12-26,2020-10-30,Positions,Ariana Grande,1,8,4.0,8,...,"{'neg': 0.039, 'neu': 0.803, 'pos': 0.157, 'co...",0.039,0.803,0.157,0.9935,pos,88,35mvY5S1H3J2QZyna3TFe0,True,57
3,3,3,2020-12-26,2020-11-20,Dynamite,BTS,1,9,24.0,17,...,"{'neg': 0.03, 'neu': 0.82, 'pos': 0.15, 'compo...",0.030,0.820,0.150,0.9946,pos,88,5QDLhrAOJJdNAmCTJ8xMyW,False,36
4,4,4,2020-12-26,2020-09-18,Holy,Justin Bieber Featuring Chance The Rapper,3,13,9.0,13,...,"{'neg': 0.07, 'neu': 0.799, 'pos': 0.131, 'com...",0.070,0.799,0.131,0.9863,pos,80,5u1n1kITHCxxp8twBcZxWy,False,99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5066,5066,5066,2010-01-02,2009-05-15,Elevator,Eminem,67,67,NaN,1,...,"{'neg': 0.128, 'neu': 0.785, 'pos': 0.087, 'co...",0.128,0.785,0.087,-0.9918,neg,52,26rUU3JZ9JB9OkEuG9mb3e,True,232
5067,5067,5067,2010-01-02,2009-01-01,On Fire,Lil Wayne,62,84,62.0,2,...,"{'neg': 0.184, 'neu': 0.681, 'pos': 0.135, 'co...",0.184,0.681,0.135,-0.9785,neg,37,50mX6QmpQX4cCsRYJ9fGM3,True,366
5068,5068,5068,2010-01-02,2009-11-24,I Get It In,Omarion Featuring Gucci Mane,83,98,92.0,7,...,"{'neg': 0.045, 'neu': 0.903, 'pos': 0.052, 'co...",0.045,0.903,0.052,-0.4019,neg,28,2E6gb0Ngrvun6CUAUkvZPI,True,39
5069,5069,5069,2019-12-21,2019-05-13,We Were,Keith Urban,65,94,66.0,15,...,"{'neg': 0.059, 'neu': 0.867, 'pos': 0.073, 'co...",0.059,0.867,0.073,0.7851,pos,55,5Net7uzpcqkJtOwR22onye,False,222
5070,5070,5070,2014-03-08,2013-06-04,Safe And Sound,Capital Cities,8,44,46.0,43,...,"{'neg': 0.015, 'neu': 0.76, 'pos': 0.225, 'com...",0.015,0.760,0.225,0.9967,pos,84,6Z8R6UsFuGXGtiIxiD8ISb,False,277

In [212]:
#df.reset_index()

In [234]:
df.to_csv (r'2010_2020_preTweet.csv', header=True)

In [214]:
#df.drop(df.columns[[0]], axis = 1, inplace = True)

In [215]:
#df

In [216]:
from datetime import datetime

In [217]:
count = 0

for i in range(0, 5071, 1):
    try:
        date1 = df['peak_date'][i]
        date2 = df['release_date'][i]
        peak = datetime.strptime(date1, "%Y-%m-%d")
        release = datetime.strptime(date2, "%Y-%m-%d")
        if peak < release:
            print (i, df['song'][i], df['artist'][i])
            count += 1
    except:
        print ("Error: ", i, df['song'][i], df['artist'][i] )

In [218]:
count

0

## Get difference between dates

In [219]:
def days_between(d1, d2):
    d1 = datetime.strptime(d1, "%Y-%m-%d")
    d2 = datetime.strptime(d2, "%Y-%m-%d")
    return abs((d2 - d1).days)

In [220]:
count = 0
diff_day = []
for x in range(0, 5071, 1):
    try:
        day = days_between(df['release_date'][x], df['peak_date'][x])
        diff_day.append(day)
        if day < 7:
            print (x, df['song'][x], df['artist'][x])
            count += 1
    except:
        diff_day.append(17000)

In [221]:
count

0

In [222]:
len(diff_day)

5071

In [223]:
diff_day

[15,
 155,
 57,
 36,
 99,
 232,
 134,
 281,
 190,
 15,
 36,
 57,
 120,
 176,
 274,
 99,
 318,
 15,
 57,
 44,
 15,
 15,
 15,
 288,
 15,
 176,
 15,
 253,
 60,
 15,
 128,
 15,
 141,
 43,
 15,
 50,
 414,
 22,
 15,
 36,
 15,
 15,
 51,
 100,
 156,
 15,
 148,
 15,
 43,
 547,
 15,
 15,
 295,
 65,
 15,
 253,
 15,
 50,
 15,
 319,
 92,
 15,
 92,
 44,
 85,
 18,
 15,
 15,
 64,
 285,
 36,
 36,
 285,
 155,
 23,
 92,
 15,
 191,
 206,
 148,
 52,
 127,
 78,
 17,
 127,
 22,
 18,
 15,
 190,
 106,
 372,
 288,
 50,
 78,
 274,
 57,
 57,
 57,
 29,
 29,
 218,
 274,
 137,
 239,
 22,
 85,
 155,
 386,
 382,
 85,
 365,
 15,
 15,
 15,
 15,
 15,
 15,
 23,
 15,
 15,
 15,
 15,
 449,
 239,
 463,
 148,
 15,
 15,
 15,
 71,
 162,
 15,
 16,
 15,
 43,
 22,
 148,
 15,
 185,
 15,
 141,
 218,
 610,
 372,
 15,
 351,
 15,
 148,
 15,
 148,
 15,
 15,
 15,
 116,
 400,
 17,
 15,
 99,
 57,
 85,
 114,
 129,
 127,
 164,
 15,
 78,
 15,
 15,
 106,
 127,
 379,
 22,
 15,
 22,
 22,
 716,
 15,
 15,
 22,
 22,
 15,
 15,
 15,
 232,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 127,
 428,
 57,
 15,
 15,
 17,
 15,
 148,
 15,
 85,
 23,
 114,
 107,
 157,
 103,
 43,
 127,
 295,
 15,
 29,
 13,
 29,
 29,
 113,
 317,
 176,
 71,
 36,
 190,
 142,
 15,
 45,
 162,
 373,
 15,
 184,
 23,
 22,
 29,
 22,
 449,
 211,
 18,
 15,
 15,
 15,
 15,
 15,
 148,
 15,
 16,
 15,
 15,
 15,
 15,
 274,
 439,
 183,
 162,
 338,
 43,
 78,
 15,
 15,
 96,
 15,
 604,
 331,
 211,
 240,
 15,
 22,
 15,
 15,
 232,
 460,
 22,
 29,
 568,
 197,
 11,
 15,
 15,
 15,
 15,
 15,
 176,
 37,
 15,
 85,
 224,
 218,
 151,
 15,
 15,
 15,
 51,
 421,
 190,
 15,
 15,
 120,
 134,
 166,
 169,
 198,
 14,
 15,
 50,
 330,
 162,
 274,
 14,
 15,
 57,
 43,
 444,
 113,
 183,
 302,
 148,
 73,
 50,
 50,
 64,
 57,
 141,
 281,
 15,
 512,
 287,
 15,
 43,
 23,
 113,
 142,
 149,
 22,
 22,
 22,
 22,
 22,
 11,
 22,
 36,
 24,
 22,
 15,
 15,
 15,
 17,
 15,
 15,
 15,
 15,
 15,
 573,
 22,
 22,
 22,
 99,
 22,
 22,
 22,
 267,
 22,
 92,
 78,
 22,
 29,
 15,
 15,
 22,
 15,
 15,
 22,
 421,
 85,
 22,
 78,
 358,
 225,
 15,
 36,
 15,
 15,
 15,
 15,
 183,
 18,
 15,
 15,
 36,
 547,
 22,
 140,
 474,
 15,
 295,
 211,
 292,
 22,
 15,
 57,
 134,
 106,
 113,
 16,
 50,
 57,
 29,
 271,
 234,
 18,
 15,
 22,
 86,
 16,
 267,
 72,
 50,
 29,
 337,
 22,
 652,
 22,
 15,
 197,
 247,
 176,
 23,
 43,
 29,
 106,
 15,
 561,
 36,
 16,
 15,
 16,
 148,
 15,
 15,
 15,
 29,
 183,
 29,
 238,
 148,
 15,
 15,
 15,
 92,
 15,
 15,
 15,
 15,
 15,
 15,
 22,
 22,
 15,
 379,
 253,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 29,
 15,
 15,
 15,
 15,
 15,
 344,
 15,
 15,
 15,
 37,
 57,
 78,
 22,
 15,
 22,
 36,
 22,
 15,
 421,
 22,
 397,
 127,
 22,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 120,
 15,
 15,
 78,
 140,
 29,
 212,
 50,
 218,
 218,
 15,
 15,
 57,
 64,
 15,
 15,
 121,
 22,
 71,
 15,
 70,
 18,
 218,
 15,
 309,
 15,
 92,
 15,
 15,
 15,
 134,
 15,
 15,
 15,
 16,
 22,
 155,
 15,
 16,
 59,
 184,
 15,
 99,
 92,
 47,
 50,
 113,
 92,
 93,
 169,
 15,
 15,
 15,
 17,
 15,
 15,
 15,
 22,
 29,
 15,
 92,
 15,
 155,
 64,
 67,
 15,
 183,
 25,
 42,
 42,
 142,
 36,
 148,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 85,
 15,
 15,
 15,
 50,
 22,
 29,
 22,
 15,
 346,
 15,
 22,
 15,
 15,
 15,
 15,
 127,
 15,
 190,
 15,
 15,
 22,
 15,
 15,
 15,
 15,
 107,
 22,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 22,
 135,
 15,
 15,
 21,
 15,
 21,
 15,
 211,
 15,
 267,
 351,
 156,
 141,
 15,
 15,
 15,
 14,
 41,
 22,
 29,
 15,
 519,
 14,
 15,
 14,
 30,
 14,
 15,
 533,
 274,
 302,
 15,
 274,
 15,
 15,
 22,
 15,
 162,
 15,
 15,
 239,
 15,
 15,
 29,
 57,
 22,
 15,
 316,
 15,
 148,
 15,
 15,
 15,
 22,
 15,
 15,
 15,
 15,
 15,
 190,
 106,
 148,
 22,
 148,
 16,
 246,
 15,
 269,
 15,
 78,
 267,
 15,
 99,
 218,
 15,
 19,
 15,
 19,
 29,
 15,
 15,
 15,
 18,
 36,
 155,
 148,
 22,
 22,
 22,
 22,
 64,
 16,
 22,
 22,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 148,
 15,
 106,
 295,
 71,
 131,
 113,
 211,
 239,
 50,
 14,
 15,
 15,
 15,
 15,
 113,
 50,
 169,
 59,
 204,
 211,
 323,
 22,
 22,
 134,
 17,
 22,
 134,
 176,
 15,
 442,
 50,
 207,
 35,
 170,
 652,
 176,
 57,
 57,
 192,
 309,
 383,
 15,
 15,
 16,
 18,
 15,
 64,
 15,
 36,
 547,
 288,
 15,
 15,
 288,
 36,
 15,
 15,
 50,
 148,
 141,
 260,
 22,
 50,
 64,
 29,
 169,
 92,
 120,
 15,
 38,
 15,
 22,
 148,
 50,
 120,
 57,
 168,
 323,
 15,
 87,
 362,
 505,
 22,
 15,
 16,
 50,
 127,
 106,
 239,
 22,
 43,
 67,
 302,
 50,
 533,
 44,
 23,
 85,
 183,
 22,
 14,
 456,
 15,
 22,
 22,
 141,
 29,
 15,
 15,
 15,
 15,
 15,
 15,
 43,
 8,
 323,
 57,
 23,
 78,
 204,
 22,
 99,
 22,
 155,
 22,
 29,
 14,
 92,
 169,
 15,
 50,
 29,
 50,
 71,
 169,
 149,
 15,
 15,
 15,
 15,
 400,
 22,
 15,
 67,
 43,
 22,
 239,
 373,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 36,
 15,
 78,
 51,
 43,
 120,
 150,
 470,
 190,
 22,
 29,
 113,
 50,
 30,
 64,
 540,
 22,
 15,
 463,
 22,
 120,
 113,
 456,
 15,
 15,
 15,
 85,
 121,
 85,
 120,
 22,
 218,
 505,
 169,
 86,
 17,
 22,
 22,
 57,
 15,
 15,
 148,
 19,
 344,
 15,
 127,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 246,
 15,
 99,
 113,
 190,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 22,
 330,
 15,
 113,
 22,
 38,
 373,
 341,
 310,
 267,
 190,
 9,
 99,
 15,
 22,
 15,
 267,
 456,
 137,
 151,
 177,
 57,
 29,
 190,
 316,
 15,
 15,
 15,
 15,
 36,
 10,
 15,
 122,
 414,
 372,
 78,
 15,
 72,
 50,
 15,
 15,
 309,
 64,
 85,
 638,
 260,
 148,
 191,
 192,
 ...]

In [224]:
min(diff_day)

8

In [225]:
max(diff_day)

726

In [226]:
import numpy as np

In [227]:
np.mean(diff_day)

149.14908302110038

In [228]:
np.median(diff_day)

99.0

In [229]:
median = max(set(diff_day), key=diff_day.count)
median

15

In [230]:
max(df['weeks_board'])

87

In [231]:
df['days'] = diff_day

In [232]:
df

,Unnamed: 0,Unnamed: 0.1,peak_date,release_date,song,artist,peak_rank,current_rank,last_rank,weeks_board,...,lyrics_score,lyrics_neg,lyrics_neu,lyrics_pos,lyrics_compound,lyrics_label,spotify_pop,spotify_id,spotify_explicit,days
0,0,0,2020-12-26,2020-12-11,Willow,Taylor Swift,1,1,NaN,1,...,"{'neg': 0.085, 'neu': 0.773, 'pos': 0.141, 'co...",0.085,0.773,0.141,0.9829,pos,82,0lx2cLdOt3piJbcaXIV74f,False,15
1,1,1,2020-12-26,2020-07-24,Mood,24kGoldn Featuring iann dior,1,5,2.0,19,...,"{'neg': 0.089, 'neu': 0.796, 'pos': 0.115, 'co...",0.089,0.796,0.115,0.9751,pos,89,4jPy3l0RUwlUI9T5XHBW2m,True,155
2,2,2,2020-12-26,2020-10-30,Positions,Ariana Grande,1,8,4.0,8,...,"{'neg': 0.039, 'neu': 0.803, 'pos': 0.157, 'co...",0.039,0.803,0.157,0.9935,pos,88,35mvY5S1H3J2QZyna3TFe0,True,57
3,3,3,2020-12-26,2020-11-20,Dynamite,BTS,1,9,24.0,17,...,"{'neg': 0.03, 'neu': 0.82, 'pos': 0.15, 'compo...",0.030,0.820,0.150,0.9946,pos,88,5QDLhrAOJJdNAmCTJ8xMyW,False,36
4,4,4,2020-12-26,2020-09-18,Holy,Justin Bieber Featuring Chance The Rapper,3,13,9.0,13,...,"{'neg': 0.07, 'neu': 0.799, 'pos': 0.131, 'com...",0.070,0.799,0.131,0.9863,pos,80,5u1n1kITHCxxp8twBcZxWy,False,99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5066,5066,5066,2010-01-02,2009-05-15,Elevator,Eminem,67,67,NaN,1,...,"{'neg': 0.128, 'neu': 0.785, 'pos': 0.087, 'co...",0.128,0.785,0.087,-0.9918,neg,52,26rUU3JZ9JB9OkEuG9mb3e,True,232
5067,5067,5067,2010-01-02,2009-01-01,On Fire,Lil Wayne,62,84,62.0,2,...,"{'neg': 0.184, 'neu': 0.681, 'pos': 0.135, 'co...",0.184,0.681,0.135,-0.9785,neg,37,50mX6QmpQX4cCsRYJ9fGM3,True,366
5068,5068,5068,2010-01-02,2009-11-24,I Get It In,Omarion Featuring Gucci Mane,83,98,92.0,7,...,"{'neg': 0.045, 'neu': 0.903, 'pos': 0.052, 'co...",0.045,0.903,0.052,-0.4019,neg,28,2E6gb0Ngrvun6CUAUkvZPI,True,39
5069,5069,5069,2019-12-21,2019-05-13,We Were,Keith Urban,65,94,66.0,15,...,"{'neg': 0.059, 'neu': 0.867, 'pos': 0.073, 'co...",0.059,0.867,0.073,0.7851,pos,55,5Net7uzpcqkJtOwR22onye,False,222
5070,5070,5070,2014-03-08,2013-06-04,Safe And Sound,Capital Cities,8,44,46.0,43,...,"{'neg': 0.015, 'neu': 0.76, 'pos': 0.225, 'com...",0.015,0.760,0.225,0.9967,pos,84,6Z8R6UsFuGXGtiIxiD8ISb,False,277